[package]
name = "converge-monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
reqwest = { version = "0.12.20", default-features = false, features = ["rustls-tls", "http2", "charset"] }
scraper = "0.23.1"
tokio = { version = "1.45.1", features = ["full"] }
