services:
  converge-monitor:
    image: ghcr.io/ggorg0/converge-monitor:master
    pull_policy: always
    build:
      context: .
    volumes:
      - ./data:/data
    env_file: .env
    restart: unless-stopped
